gazebo_ros_control:
  pid_gains:
    r_arm_joint1: { p: 100.0,  d: 0, i: 0.0 }
    r_arm_joint2: { p: 100.0,  d: 0, i: 0.0 }
    r_arm_joint3: { p: 100.0,  d: 0, i: 0.0 }
    r_arm_joint4: { p: 100.0,  d: 0, i: 0.0 }
    r_arm_joint5: { p: 100.0,  d: 0, i: 0.0 }
    r_arm_joint6: { p: 100.0,  d: 0, i: 0.0 }
    r_arm_joint7: { p: 100.0,  d: 0, i: 0.0 }
    l_arm_joint1: { p: 100.0,  d: 0, i: 0.0 }
    l_arm_joint2: { p: 100.0,  d: 0, i: 0.0 }
    l_arm_joint3: { p: 100.0,  d: 0, i: 0.0 }
    l_arm_joint4: { p: 100.0,  d: 0, i: 0.0 }
    l_arm_joint5: { p: 100.0,  d: 0, i: 0.0 }
    l_arm_joint6: { p: 100.0,  d: 0, i: 0.0 }
    l_arm_joint7: { p: 100.0,  d: 0, i: 0.0 }
    neck_yaw_joint: { p: 100.0,  d: 0, i: 0.0 }
    neck_pitch_joint: { p: 100.0,  d: 0, i: 0.0 }
    waist_yaw_joint: { p: 100.0,  d: 0, i: 0.0 }
